#EnsJobeetBundle_job:
#    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
#    prefix: /job

EnsJobeetBundle:
    resource: "@EnsJobeetBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin