ens_category:
    path:     /
    defaults: { _controller: "EnsJobeetBundle:Category:index" }

ens_category_show:
    path:     /{id}/show
    defaults: { _controller: "EnsJobeetBundle:Category:show" }

ens_category_new:
    path:     /new
    defaults: { _controller: "EnsJobeetBundle:Category:new" }

ens_category_create:
    path:     /create
    defaults: { _controller: "EnsJobeetBundle:Category:create" }
    requirements: { _method: post }

ens_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnsJobeetBundle:Category:edit" }

ens_category_update:
    path:     /{id}/update
    defaults: { _controller: "EnsJobeetBundle:Category:update" }
    requirements: { _method: post|put }

ens_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnsJobeetBundle:Category:delete" }
    requirements: { _method: post|delete }
